services:
    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: ${APP_SLUG}_nginx
        hostname: ${APP_SLUG}_nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "443:443"
        links:
          - php-fpm
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        networks:
          - ${APP_SLUG}_network
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
        image: php:${PHP_VERSION}
        container_name: ${APP_SLUG}_php-fpm
        hostname: ${APP_SLUG}_php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        cap_add:
          - SYS_NICE
          - DAC_READ_SEARCH
        networks:
          - ${APP_SLUG}_network
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${APP_SLUG}_mysql
        hostname: ${APP_SLUG}_mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
          - ${APP_SLUG}_network
networks:
  [REPLACE_WITH_SLUG]_network:
    external: true
